// Example 96
// generator/main.go
package main

import (
    "log"
    "os"
    "text/template"
)

type Field struct {
    Name string
    Type string
}

type Struct struct {
    Name   string
    Fields []Field
}

const tmpl = `
// Code generated by generator; DO NOT EDIT.
package {{.Package}}

type {{.Name}} struct {
    {{range .Fields}}
    {{.Name}} {{.Type}}
    {{end}}
}
`

func main() {
    // Parse template and generate code
    t := template.Must(template.New("struct").Parse(tmpl))
    
    data := Struct{
        Name: "User",
        Fields: []Field{
            {"ID", "string"},
            {"Name", "string"},
            {"Age", "int"},
        },
    }
    
    f, err := os.Create("generated.go")
    if err != nil {
        log.Fatal(err)
    }
    defer f.Close()
    
    if err := t.Execute(f, data); err != nil {
        log.Fatal(err)
    }
}